bootstrap/urls.py
from django.conf.urls import url,patterns
from bootstrap import views


#add app_name
app_name = 'bootstrap'

#urlpatterns = [

#    url(r'^$', views.Index, name='index'),
#    url(r'^name/$', views.get_name, name='get_name'),
#    url(r'^list/$', views.list, name='list'),   
#    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
#    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

#]

urlpatterns = [
#    url(r'^$', views.IndexView.as_view(), name='index'),
#    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
#    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
#    url(r'^list/$', views.list, name='list'),
#    url(r'^login/$', views.login, name='login'),
#    url(r'^regist/$', views.regist, name='regist'),
#    url(r'index/$', views.index, name='index'),
#    url(r'logout/$', views.logout, name='logout'),
#    url(r'^excel/$', views.uploadExcel, name='excel'),
    url(r'^exceltodb/$', views.importdb, name='exceldb'),
    url(r'^sheettodb/$', views.import_sheet, name='sheetdb'),
    url(r'^sheet_safe/$', views.import_safe, name='safe'),
]

'''
from django.conf.urls import patterns, include, url   
  
urlpatterns = patterns('bootstrap.views',  
    url(r'^list/$', 'list', name='list'),  
)  
'''

mysite/urls.py
from django.conf.urls import url,include,patterns
from django.contrib import admin
from django.views.generic import RedirectView 
from django.conf.urls.static import static  
from django.conf import settings 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls')),
    url(r'^bootstrap/',include('bootstrap.urls')),
    url(r'^$', RedirectView.as_view(url='/bootstrap/list/')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)       


'''
urlpatterns = patterns('',  
    (r'^bootstrap/', include('bootstrap.urls')),  
    (r'^$', RedirectView.as_view(url='/mysite/bootstrap/list/')), # Just for ease of use.  
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
'''

polls/urls.py
from django.conf.urls import url
from  polls  import views

#add app_name
app_name = 'polls'
'''
urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

]
'''
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

bootstrap/models.py
from django.db import models

# Create your models here.

class Document(models.Model):
    docfile = models.FileField(upload_to='documents/%Y/%m/%d')

class User(models.Model):
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __unicode__(self):
        return self.username

bootstrap/forms/addFile.py
from django import forms

class DocumentForm(forms.Form):
    docfile = forms.FileField(
        label = 'select a file',
        help_text='max 42 mb'
    )

class ExcelForm(forms.Form):
    excelfile = forms.FileField(
        label = 'select a file',
        help_text= 'max 42 mb'
    )

bootstrap/forms/addName.py
from django import forms

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your Name', max_length=100)

bootstrap/forms/regUser.py
from django import forms


class RegUser(forms.Form):
    username = forms.CharField(label='用户名',max_length=100)
    password = forms.CharField(label='密码',widget=forms.PasswordInput())

bootstrap/views.py
from django.shortcuts import render_to_response  
#中文测试
from django.template import RequestContext  
from django.http import HttpResponseRedirect,HttpResponse 
from django.core.urlresolvers import reverse  

import pyexcel.ext.xls
import django_excel
import pyexcel.ext.xlsx
import pyexcel
from .models import Document  
from .model.t_Ticket import T_ticket
from .forms.addFile import DocumentForm  
from .forms.addName import NameForm
from .forms.regUser import RegUser
from .models import User
from .forms.addFile import ExcelForm 
from .model.t_Question import Question
from .model.t_Question import Choice
def list(request):  
    # Handle file upload  
    if request.method == 'POST':  
        form = DocumentForm(request.POST, request.FILES)  
        if form.is_valid():  
            newdoc = Document(docfile = request.FILES['docfile'])  
            newdoc.save()  
  
            # Redirect to the document list after POST  
            return HttpResponseRedirect(reverse('bootstrap:list'))  
    else:  
        form = DocumentForm() # A empty, unbound form  
  
    # Load documents for the list page  
    documents = Document.objects.all()  
  
    # Render list page with the documents and the form  
    return render_to_response(  
        'bootstrap/list.html',  
        {'documents': documents, 'form': form},  
        context_instance=RequestContext(request)  
    )  

def regist(req):
    if req.method =='POST':
        uf = RegUser(req.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            User.objects.create(username=username,password=password)
            f = open('/data/dennie/pythontest/lib/python3.5/site-packages/django/bin/mysite/media/documents/2016/03/a.txt',encoding="utf-8")
            TickList = []
            for line in f:
                (ticket_id, channel, user_uin , own_uin, own_name, own_phone,
                user_type, service_combination, service, service_situation,
                label_one, label_two, label_Three, question, answer, effect_level,
                functional_correlation, handel_person, team, level, start_time,
                queue_time, response_time, total_time, levelone_t, leveltwo_t,
                levelthree_t, levelFore_t, customer_evaluation, ticket_ctime,
                session_id, job_number, ticket_status, tosb, is_solved, comment) = line.split(',')
                ticket = T_ticket(ticket_id=ticket_id, channel=channel,
                             user_uin=user_uin , own_uin=own_uin,
                             own_name=own_name, own_phone=own_phone,
                             user_type=user_type,
                             service_combination=service_combination,
                             service=service,
                             service_situation=service_situation,
                             label_one=label_one, label_two=label_two,
                             label_Three=label_Three, question=question,
                             answer=answer, effect_level=effect_level,
                             functional_correlation=functional_correlation,
                             handel_person=handel_person, team=team,
                             level=level, start_time=start_time,
                             queue_time=queue_time,
                             response_time=response_time,
                             total_time=total_time, levelone_t=levelone_t,
                             leveltwo_t=levelthree_t,
                             levelthree_t=levelthree_t,
                             levelFore_t=levelFore_t,
                             customer_evaluation=customer_evaluation,
                             ticket_ctime=ticket_ctime, session_id=session_id,
                             job_number=job_number,
                             ticket_status=ticket_status, tosb=tosb,
                             is_solved=is_solved, comment=comment
                             )

                TickList.append(ticket)
            f.close()

            T_ticket.objects.bulk_create(TickList)
            #T_ticket.objects.create(ticket_id=554536,user_uin=123456789)
            return HttpResponse('regist success')
    else:
        uf = RegUser()
    return render_to_response(
        'bootstrap/register.html',
        {'uf': uf},
        context_instance=RequestContext(req),
     )


def login(req):
    if req.method == 'POST':
        uf = RegUser(req.POST)
        if uf.is_valid():
            username = uf.cleaned_data['username']
            password = uf.cleaned_data['password']
            user=User.objects.filter(username__exact = username,password__exact
                                     = password)
            if user:
                response = HttpResponseRedirect('/bootstrap/index')
                response.set_cookie('username',username,3600)
                return response
            else:
                return HttpResponseRedirect('/bootstrap/login')
    else:
        uf = RegUser()
    return render_to_response(
        'bootstrap/login.html',
        {'uf':uf},
        context_instance=RequestContext(req)
    )

def index(req):
    username = req.COOKIES.get('username','')
    return render_to_response(
        'bootstrap/index.html',
        {'username':username}
    )


def logout(req):
    #response = HttpResponse('logout!!')
    # response.delete_cookie('usename')
    #uf = RegUser()
    #return render_to_response(
    #    'bootstrap/login.html',
    #    {'uf':uf},
    #    context_instance=RequestContext(req),
    #    'bootstrap/index.html',¬
    #     {'username':username}¬

    # )
   response = HttpResponseRedirect('/bootstrap/index')
   response.delete_cookie('username')
   return response


def uploadExcel(request):
    if request.method == 'POST':
        form = ExcelForm(request.POST,request.FILES)
        if form.is_valid():
            filehandle = request.FILES['excelfile']
            return django_excel.make_response(filehandle.get_sheet(), "csv",
                                       file_name="download" )
    else:
        form = ExcelForm()
    return render_to_response("bootstrap/upload_form.html",
        {'form':form}, context_instance=RequestContext(request)
    )

def importdb(request):
    if request.method == 'POST':
        form = ExcelForm(request.POST, request.FILES)
        def choice_func(row):
            q=Question.objects.filter(slug=row[0])[0]
            row[0] = q
            return row
        if form.is_valid():
            request.FILES['excelfile'].save_book_to_database(
                models=[Question, Choice],
                initializers=[None, choice_func],
                mapdicts=[
                    ['question_text', 'pub_date', 'slug'],
                    ['question', 'choice_text', 'votes']]
            )

            return HttpResponse('ok', status=200)
        else:
            return HttpResponseBadRequest()
    else:
        form = ExcelForm()
    return render_to_response("bootstrap/upload_db.html", {'form':form},
        context_instance=RequestContext(request),
         )

def import_sheet(request):
    if request.method == "POST":
        form = ExcelForm(
            request.POST,
            request.FILES
        )
        if form.is_valid():
            request.FILES['excelfile'].save_to_database(
                name_columns_by_row=2,
                model=Question,
                mapdict=['question_text', 'pub_date', 'slug'])
            '''
                mapdict={"Question Text": "question_text",
                           "Publish Date": "pub_date",
                         "测试": "slug"}
            )
            '''
            return HttpResponse("OK",status=200)
        else:
            return HttpResponseBadRequest()
    else:
        form = ExcelForm()
    return render_to_response('bootstrap/sheet_db.html',
                              {'form': form},
                              context_instance=RequestContext(request))


def import_safe(request):
    if request.method == "POST":
        form = ExcelForm(request.POST,
                              request.FILES)
        if form.is_valid():
            request.FILES['excelfile'].save_to_database(
                name_columns_by_row=0,
                model=T_ticket,
                mapdict=['ticket_id', 'channel', 'user_uin', 'own_uin', 'own_name', 
				'own_phone','user_type', 'service_combination', 'service', 
				'service_situation', 'label_one', 'label_two', 'label_Three', 'question',
				'answer', 'effect_level', 'functional_correlation', 'handel_person', 'team',
				'level', 'start_time','queue_time', 'response_time', 'total_time', 
				'levelone_t', 'leveltwo_t','levelthree_t', 'levelFore_t', 'customer_evaluation', 
				'ticket_ctime', 'session_id', 'job_number', 'ticket_status', 'tosb',
				'is_solved', 'comment'])
            return HttpResponse("OK")
        else:
            return HttpResponseBadRequest()
    else:
        form = ExcelForm()
    return render_to_response('bootstrap/sheet_safe.html',
                              {'form': form},
                              context_instance=RequestContext(request))

bootstrap/templates/bootstrap/index.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
            />
                <title></title>
            </head>

            <body>
                <h1>welcome {{username}} !</h1>
                <br>
                <a href="{%url 'bootstrap:logout'%}">退出</a>
            </body>
        </html>

bootstrap/templates/bootstrap/index2.html
{% load staticfiles %}


<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap 实例</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}" />   
</head>
<body>

<div class="container">
 <p>下载图标：<span class="glyphicon glyphicon-download"></span></p> 
  <div class="jumbotron">
    <h1>我的第一个 Bootstrap 页面</h1>
    <p>重置窗口大小，查看响应式效果！</p> 
  </div>
  <div class="row">
    <div class="col-sm-4">
      <h3>第一列</h3>
      <p>学的不仅是技术，更是梦想！</p>
      <p>再牛逼的梦想,也抵不住你傻逼似的坚持！</p>
    </div>
    <div class="col-sm-4">
      <h3>第二列{{ datetime }}</h3>
      <p>学的不仅是技术，更是梦想！</p>
      <p>再牛逼的梦想,也抵不住你傻逼似的坚持！</p>
    </div>
    <div class="col-sm-4">
      <h3>第三列</h3>        
      <p>学的不仅是技术，更是梦想！</p>
      <p>再牛逼的梦想,也抵不住你傻逼似的坚持！</p>
    </div>
  </div>
</div>
<script src="{% static 'jquery/jquery.js' %}" />
<script src="{% static 'bootstrap/js/bootstrap.js' %}" />
</body>
</html>

bootstrap/templates/bootstrap/list.html
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title>Minimal Django File Upload Example</title>     
    </head>  
  
    <body>  
        <!-- List of uploaded documents -->  
        {% if documents %}  
            <ul>  
            {% for document in documents %}  
                <li><a href="{{ document.docfile.url }}">{{ document.docfile.name }}</a></li>  
            {% endfor %}  
            </ul>  
        {% else %}  
            <p>No documents.</p>  
        {% endif %}  
  
        <!-- Upload form. Note enctype attribute! -->  
        <form action="{% url 'bootstrap:list'  %}"  method="post" enctype="multipart/form-data">  
            {% csrf_token %}  
            <p>{{ form.non_field_errors }}</p>  
            <p>{{ form.docfile.label_tag }} {{ form.docfile.help_text }}</p>  
            <p>  
                {{ form.docfile.errors }}  
                {{ form.docfile }}  
            </p>  
            <p><input type="submit" value="Upload" /></p>  
        </form>  
          
    </body>  
  
</html>  

bootstrap/templates/bootstrap/login.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
            />
                <title>登陆</title>
            </head>

            <body>
                <h1>登陆页面：</h1>
                <form method = 'post' enctype="multipart/form-data">
                        {% csrf_token %}
                            {{uf.as_p}}
                                <input type="submit" value = "ok" />
                            </form>
                            <br>
                            <a href="{% url 'bootstrap:regist'%}">注册
                            </a>
                        </body>
                    </html>

bootstrap/templates/bootstrap/name.html
{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{# Display a form #}

{% load staticfiles %}

<form action="/url/to/submit/" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}
</form>
<script src="{% static 'jquery/jquery.js' %}" />
{% bootstrap_javascript %}

bootstrap/templates/bootstrap/register.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"
            />
                <title>注册</title>
            </head>

            <body>
                <h1>注册页面：</h1>
                <form method = 'post' enctype="multipart/form-data">
                        {% csrf_token %}
                            {{uf.as_p}}
                                <input type="submit" value = "ok" />
                            </form>
                            <br>
                            <a href="{% url 'bootstrap:login'%}">登陆
                            </a>
                        </body>
                    </html>

bootstrap/templates/bootstrap/sheet_db.html
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title>Minimal Django File Upload Example</title>     
    </head>  
  
    <body>  
  
        <!-- Upload form. Note enctype attribute! -->  
        <form action="{% url 'bootstrap:sheetdb'  %}"  method="post" enctype="multipart/form-data">  
            {% csrf_token %}  
            <p>{{ form.non_field_errors }}</p>  
            <p>{{ form.excelfile.label_tag }} {{ form.excelfile.help_text }}</p>  
            <p>  
                {{ form.excelfile.errors }}  
                {{ form.excelfile }}  
            </p>  
            <p><input type="submit" value="Upload" /></p>  
        </form>  
          
    </body>  
  
</html>  

bootstrap/templates/bootstrap/sheet_safe.html
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title>Minimal Django File Upload Example</title>     
    </head>  
  
    <body>  
  
        <!-- Upload form. Note enctype attribute! -->  
        <form action="{% url 'bootstrap:safe'  %}"  method="post" enctype="multipart/form-data">  
            {% csrf_token %}  
            <p>{{ form.non_field_errors }}</p>  
            <p>{{ form.excelfile.label_tag }} {{ form.excelfile.help_text }}</p>  
            <p>  
                {{ form.excelfile.errors }}  
                {{ form.excelfile }}  
            </p>  
            <p><input type="submit" value="Upload" /></p>  
        </form>  
          
    </body>  
  
</html>  

bootstrap/templates/bootstrap/upload_db.html
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title>Minimal Django File Upload Example</title>     
    </head>  
  
    <body>  
  
        <!-- Upload form. Note enctype attribute! -->  
        <form action="{% url 'bootstrap:exceldb'  %}"  method="post" enctype="multipart/form-data">  
            {% csrf_token %}  
            <p>{{ form.non_field_errors }}</p>  
            <p>{{ form.excelfile.label_tag }} {{ form.excelfile.help_text }}</p>  
            <p>  
                {{ form.excelfile.errors }}  
                {{ form.excelfile }}  
            </p>  
            <p><input type="submit" value="Upload" /></p>  
        </form>  
          
    </body>  
  
</html>  

bootstrap/templates/bootstrap/upload_form.html
<!DOCTYPE html>  
<html>  
    <head>  
        <meta charset="utf-8">  
        <title>Minimal Django File Upload Example</title>     
    </head>  
  
    <body>  
  
        <!-- Upload form. Note enctype attribute! -->  
        <form action="{% url 'bootstrap:excel'  %}"  method="post" enctype="multipart/form-data">  
            {% csrf_token %}  
            <p>{{ form.non_field_errors }}</p>  
            <p>{{ form.excelfile.label_tag }} {{ form.excelfile.help_text }}</p>  
            <p>  
                {{ form.excelfile.errors }}  
                {{ form.excelfile }}  
            </p>  
            <p><input type="submit" value="Upload" /></p>  
        </form>  
          
    </body>  
  
</html>  